services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9876:9876'
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_CHOICE=${MODEL_CHOICE:-gpt-4o-mini}
      - PORT=9876
    container_name: agents-playground
    restart: unless-stopped
